version: "3.8" # composeファイルのバージョン
services: 
  mysql: # サービス名
    platform: linux/amd64 
    image: mysql:8.0.29
    environment: 
      MYSQL_ROOT_PASSWORD: rootpass
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql # タイムゾーン docker-compose downでコンテナを一回落とすとデータは消えてしまうのを改善する /dataディレクトリができる ローカルに残す方法

